# Generated by Django 2.1.2 on 2018-10-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0003_remove_attraction_teste'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristattraction',
            name='attractions',
            field=models.ManyToManyField(to='attractions.Attraction'),
        ),
    ]
