# Generated by Django 2.1.2 on 2018-10-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20181005_1643'),
        ('core', '0002_touristattraction_attractions'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristattraction',
            name='comentarios',
            field=models.ManyToManyField(to='comments.Comment'),
        ),
    ]
