# Generated by Django 2.1.2 on 2018-10-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adresses', '0001_initial'),
        ('core', '0004_auto_20181005_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristattraction',
            name='adresses',
            field=models.ManyToManyField(to='adresses.Adress'),
        ),
    ]
