# Generated by Django 2.1.2 on 2018-10-05 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adresses', '0001_initial'),
        ('core', '0005_touristattraction_adresses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touristattraction',
            name='adresses',
        ),
        migrations.AddField(
            model_name='touristattraction',
            name='adresses',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adresses.Adress'),
            preserve_default=False,
        ),
    ]
