# Generated by Django 2.1.2 on 2018-12-08 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20181005_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristattraction',
            name='adresses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adresses.Adress'),
        ),
    ]
