# Generated by Django 2.1.4 on 2018-12-08 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20181208_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristattraction',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pontos_turisticos'),
        ),
    ]
