# Generated by Django 2.1.2 on 2018-10-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='teste',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
